"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { emailsApi } from "@/lib/api";
import { cn } from "@/lib/utils";
import {
  Loader2,
  CheckCircle2,
  Edit2,
  Send,
  Save,
  CheckSquare,
  Square
} from "lucide-react";
import Link from "next/link";

interface Draft {
  id: number;
  lead_id: number;
  lead_firma: string | null;
  betreff: string;
  inhalt: string;
  status: string;
}

export default function DraftsPage() {
  const queryClient = useQueryClient();
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editSubject, setEditSubject] = useState("");
  const [editBody, setEditBody] = useState("");

  const { data: drafts, isLoading } = useQuery<Draft[]>({
    queryKey: ["drafts"],
    queryFn: emailsApi.listDrafts,
  });

  const bulkApproveMutation = useMutation({
    mutationFn: (ids: number[]) => emailsApi.bulkApproveDrafts(ids),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drafts"] });
      setSelectedIds([]);
    },
  });

  const updateDraftMutation = useMutation({
    mutationFn: (data: { id: number; subject: string; body: string }) =>
      emailsApi.updateDraft(data.id, { subject: data.subject, body: data.body }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["drafts"] });
      setEditingId(null);
    },
  });

  const toggleSelection = (id: number) => {
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
    );
  };

  const selectAll = () => {
    if (!drafts) return;
    if (selectedIds.length === drafts.length) {
      setSelectedIds([]);
    } else {
      setSelectedIds(drafts.map((d) => d.id));
    }
  };

  const handleEdit = (d: Draft) => {
    setEditingId(d.id);
    setEditSubject(d.betreff);
    setEditBody(d.inhalt);
  };

  const handleSave = (id: number) => {
    updateDraftMutation.mutate({ id, subject: editSubject, body: editBody });
  };

  const handleSingleApprove = (id: number) => {
    bulkApproveMutation.mutate([id]);
  };

  const handleBulkApprove = () => {
    if (selectedIds.length > 0) {
      bulkApproveMutation.mutate(selectedIds);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">AI Outgoing Queue</h1>
          <p className="text-muted-foreground mt-1 text-sm">
            Review, edit, and approve hyper-personalized emails generated by the AI Engine.
          </p>
        </div>

        <div className="flex gap-2">
          <button
            onClick={handleBulkApprove}
            disabled={selectedIds.length === 0 || bulkApproveMutation.isPending}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-md font-medium transition-colors",
              selectedIds.length > 0 && !bulkApproveMutation.isPending
                ? "bg-accent text-accent-foreground hover:bg-accent/90"
                : "bg-muted text-muted-foreground cursor-not-allowed"
            )}
          >
            {bulkApproveMutation.isPending ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Send className="w-5 h-5" />
            )}
            Approve & Send Selected ({selectedIds.length})
          </button>
        </div>
      </div>

      {/* Main Content */}
      {isLoading ? (
        <div className="flex justify-center items-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-accent" />
        </div>
      ) : drafts?.length === 0 ? (
        <div className="rounded-xl border border-border/50 bg-card p-12 text-center text-muted-foreground flex flex-col items-center">
          <CheckCircle2 className="w-12 h-12 mb-4 text-emerald-500/50" />
          <h3 className="text-lg font-medium text-foreground mb-1">Queue Empty</h3>
          <p className="text-sm max-w-sm">
            All AI-generated outreach drafts have been processed. New drafts will appear here when active campaigns trigger their next step.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="flex items-center gap-2 px-2">
            <button
              onClick={selectAll}
              className="text-muted-foreground hover:text-foreground flex items-center gap-2 text-sm font-medium transition-colors"
            >
              {selectedIds.length === drafts?.length && drafts?.length > 0 ? (
                <CheckSquare className="w-5 h-5 text-accent" />
              ) : (
                <Square className="w-5 h-5" />
              )}
              Select All
            </button>
          </div>

          <div className="grid grid-cols-1 gap-4">
            {drafts?.map((draft) => {
              const isSelected = selectedIds.includes(draft.id);
              const isEditing = editingId === draft.id;

              return (
                <div
                  key={draft.id}
                  className={cn(
                    "rounded-xl border p-5 transition-all",
                    isSelected
                      ? "border-accent/50 bg-accent/5"
                      : "border-border/50 bg-card hover:border-border"
                  )}
                >
                  <div className="flex gap-4">
                    <button
                      onClick={() => toggleSelection(draft.id)}
                      className="mt-1 shrink-0 text-muted-foreground hover:text-accent transition-colors"
                    >
                      {isSelected ? (
                        <CheckSquare className="w-5 h-5 text-accent" />
                      ) : (
                        <Square className="w-5 h-5" />
                      )}
                    </button>

                    <div className="flex-1 space-y-4">
                      {/* Draft Header */}
                      <div className="flex justify-between items-start">
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-500 border border-blue-500/20">
                              DRAFT
                            </span>
                            <Link href={`/leads/${draft.lead_id}`} className="font-semibold text-lg hover:text-accent transition-colors">
                              {draft.lead_firma || "Unbekannte Firma"}
                            </Link>
                          </div>
                          {!isEditing && (
                            <h3 className="text-foreground mt-2 font-medium">RE: {draft.betreff}</h3>
                          )}
                        </div>
                        <div className="flex gap-2">
                          <button
                            onClick={() => (isEditing ? handleSave(draft.id) : handleEdit(draft))}
                            disabled={updateDraftMutation.isPending}
                            className={cn(
                              "p-2 rounded-md transition-colors",
                              isEditing
                                ? "bg-accent/10 text-accent hover:bg-accent/20"
                                : "text-muted-foreground hover:text-foreground hover:bg-accent/10"
                            )}
                          >
                            {isEditing ? (
                              updateDraftMutation.isPending && editingId === draft.id ? (
                                <Loader2 className="w-4 h-4 animate-spin" />
                              ) : (
                                <Save className="w-4 h-4" />
                              )
                            ) : (
                              <Edit2 className="w-4 h-4" />
                            )}
                          </button>
                          {!isEditing && (
                            <button
                              onClick={() => handleSingleApprove(draft.id)}
                              className="p-2 rounded-md text-emerald-500 hover:bg-emerald-500/10 hover:text-emerald-400 transition-colors"
                              title="Approve & Send immediately"
                            >
                              <Send className="w-4 h-4" />
                            </button>
                          )}
                        </div>
                      </div>

                      {/* Content Edit or View */}
                      {isEditing ? (
                        <div className="space-y-3">
                          <input
                            type="text"
                            value={editSubject}
                            onChange={(e) => setEditSubject(e.target.value)}
                            className="w-full bg-background border border-border/50 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent/50"
                            placeholder="Subject"
                          />
                          <textarea
                            value={editBody}
                            onChange={(e) => setEditBody(e.target.value)}
                            className="w-full h-40 bg-background border border-border/50 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent/50 resize-y"
                            placeholder="Email body"
                          />
                        </div>
                      ) : (
                        <div className="bg-background/50 rounded-lg p-4 border border-border/30 text-sm text-foreground/80 whitespace-pre-wrap font-mono relative overflow-hidden group">
                          {draft.inhalt}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
