"""Marketing Ideas -- 140 proven marketing strategies with AidSec-specific metadata."""
from typing import List, Dict, Optional


IDEA_CATEGORIES = [
    "Content & SEO",
    "Competitor & Comparison",
    "Free Tools & Engineering",
    "Paid Advertising",
    "Social Media & Community",
    "Email Marketing",
    "Partnerships & Programs",
    "Events & Speaking",
    "PR & Media",
    "Launches & Promotions",
    "Product-Led Growth",
    "Content Formats",
    "Unconventional & Creative",
    "Platforms & Marketplaces",
    "International & Localization",
    "Developer & Technical",
    "Audience-Specific",
]

BUDGET_LABELS = {"free": "Kostenlos", "low": "Niedrig", "medium": "Mittel", "high": "Hoch"}
TIMELINE_LABELS = {"quick": "Schnell", "medium": "Mittelfristig", "long": "Langfristig"}
STAGE_LABELS = {
    "pre_launch": "Pre-Launch",
    "early": "Frühphase",
    "growth": "Wachstum",
    "scale": "Skalierung",
}

# fmt: off
MARKETING_IDEAS: List[Dict] = [
    # ── Content & SEO ──────────────────────────────────────────────
    {"nr": 3, "name": "Easy Keyword Ranking", "cat": "Content & SEO",
     "desc": "Nischen-Keywords mit wenig Wettbewerb anvisieren. Long-Tail-Anfragen und aufkommende Themen finden, die Konkurrenten übersehen.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Keyword-Recherche mit Ubersuggest/Ahrefs", "Blog-Artikel zu Nischen-Sicherheitsthemen erstellen", "Content-Cluster aufbauen"],
     "aidsec": "Ideal: Keywords wie 'Arztpraxis Website Sicherheit', 'nDSG WordPress' ranken"},
    {"nr": 7, "name": "SEO Audit", "cat": "Content & SEO",
     "desc": "Umfassende technische SEO-Audits der eigenen Seite durchführen und Ergebnisse öffentlich teilen.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Eigene Website mit Screaming Frog auditieren", "Ergebnisse als Blog-Post veröffentlichen", "Fix-Dokumentation als Autorität nutzen"],
     "aidsec": "Kombinierbar mit Security-Audit-Ergebnissen als Content-Marketing"},
    {"nr": 39, "name": "Glossary Marketing", "cat": "Content & SEO",
     "desc": "Umfassendes Glossar mit Branchenbegriffen erstellen. Jeder Begriff wird eine SEO-optimierte Seite für 'Was ist X'-Suchen.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Top 50 Cybersecurity-Begriffe identifizieren", "Je eine optimierte Seite erstellen", "Interne Verlinkung aufbauen"],
     "aidsec": "Glossar: Security Headers, CSP, HSTS, nDSG — perfekt für Aufklärung"},
    {"nr": 40, "name": "Programmatic SEO", "cat": "Content & SEO",
     "desc": "Template-basierte Seiten im grossen Massstab für Keyword-Muster erstellen. Standort-, Vergleichs- oder Integrationsseiten.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Template für Stadtseiten erstellen ('Website-Sicherheit Zürich')", "Automatisierte Generierung mit Lead-Daten", "Interne Verlinkung zu Hauptseiten"],
     "aidsec": "Seiten wie 'Arztpraxis Sicherheit [Stadt]' für jede Schweizer Stadt"},
    {"nr": 41, "name": "Content Repurposing", "cat": "Content & SEO",
     "desc": "Einen Inhalt in mehrere Formate umwandeln. Blog → Twitter-Thread → YouTube-Video → Podcast → Infografik.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Besten Blog-Artikel identifizieren", "In LinkedIn-Post und Twitter-Thread umwandeln", "Video-Version für YouTube erstellen"],
     "aidsec": "Security-Analysen als Blog, LinkedIn-Post und Video wiederverwerten"},
    {"nr": 56, "name": "Proprietary Data Content", "cat": "Content & SEO",
     "desc": "Einzigartige Produkt-Daten für originale Forschung und Berichte nutzen. Nicht replizierbare Daten schaffen verlinkbare Assets.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Anonymisierte Ranking-Daten aggregieren", "Schweizer Sicherheits-Report veröffentlichen", "Jährlich wiederholen"],
     "aidsec": "Report: 'Sicherheitslage Schweizer Arztpraxen-Websites 2026' — einzigartige Daten aus dem Dashboard"},
    {"nr": 67, "name": "Internal Linking", "cat": "Content & SEO",
     "desc": "Strategische interne Verlinkung verteilt Autorität und verbessert die Crawlbarkeit. Thematische Cluster aufbauen.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Bestehende Seiten nach Themen gruppieren", "Interne Links zwischen verwandten Inhalten setzen", "Pillar-Pages erstellen"],
     "aidsec": "Sicherheitsthemen zu Clustern verbinden: Header → nDSG → Branchenspezifisch"},
    {"nr": 73, "name": "Content Refreshing", "cat": "Content & SEO",
     "desc": "Bestehende Inhalte regelmässig mit neuen Daten, Beispielen und Erkenntnissen aktualisieren.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Älteste/wichtigste Artikel identifizieren", "Aktuelle Statistiken und Beispiele einbauen", "Veröffentlichungsdatum aktualisieren"],
     "aidsec": "Security-Artikel mit neuesten Bedrohungsdaten aktualisieren"},
    {"nr": 74, "name": "Knowledge Base SEO", "cat": "Content & SEO",
     "desc": "Hilfedokumentation für die Suche optimieren. Support-Artikel, die Problem-Lösung-Anfragen ansprechen.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["FAQ-Sektion auf Website erstellen", "Häufige Kundenfragen als Artikel beantworten", "Schema-Markup hinzufügen"],
     "aidsec": "FAQ: 'Wie prüfe ich meine Security Headers?' — zieht Leads organisch an"},
    {"nr": 137, "name": "Parasite SEO", "cat": "Content & SEO",
     "desc": "Inhalte auf hochautoritativen Plattformen (Medium, LinkedIn, Substack) veröffentlichen, die schneller ranken als die eigene Domain.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["LinkedIn-Artikel über Website-Sicherheit schreiben", "Medium-Blog mit AidSec-Branding erstellen", "Traffic zurück zur Hauptseite leiten"],
     "aidsec": "LinkedIn-Artikel: 'Warum Ihre Praxis-Website ein Sicherheitsrisiko ist'"},

    # ── Competitor & Comparison ────────────────────────────────────
    {"nr": 2, "name": "Competitor Comparison Pages", "cat": "Competitor & Comparison",
     "desc": "Detaillierte Vergleichsseiten erstellen. '[Produkt] vs [Konkurrent]' und '[Konkurrent] Alternativen' Seiten.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Top 3-5 Konkurrenten identifizieren", "Vergleichsseiten erstellen", "Differenzierung klar herausarbeiten"],
     "aidsec": "Vergleiche: 'AidSec vs Sucuri', 'AidSec vs Wordfence' für WordPress-Sicherheit"},
    {"nr": 4, "name": "Marketing Jiu-Jitsu", "cat": "Competitor & Comparison",
     "desc": "Schwächen der Konkurrenz in eigene Stärken verwandeln. Bei Preiserhöhungen auf Erschwinglichkeit setzen.",
     "budget": "free", "time": "quick", "stages": ["early", "growth", "scale"],
     "how": ["Konkurrenz-Schwächen identifizieren (Preis, Komplexität)", "Eigene Stärke als Gegenposition formulieren", "Gezielte Kampagnen starten"],
     "aidsec": "AidSec-Vorteil: Schweizer Anbieter, persönlich, in 24h erledigt — vs. ausländische SaaS-Tools"},
    {"nr": 38, "name": "Competitive Ad Research", "cat": "Competitor & Comparison",
     "desc": "Konkurrenz-Werbung mit Tools wie SpyFu oder Facebook Ad Library analysieren. Was funktioniert, verbessern.",
     "budget": "low", "time": "quick", "stages": ["growth", "scale"],
     "how": ["SpyFu/SEMrush für Konkurrenz-Keywords nutzen", "Facebook Ad Library durchsuchen", "Erfolgreiche Botschaften adaptieren"],
     "aidsec": "Analysieren was Schweizer Security-Firmen bewerben und Lücken finden"},

    # ── Free Tools & Engineering ───────────────────────────────────
    {"nr": 5, "name": "Side Projects as Marketing", "cat": "Free Tools & Engineering",
     "desc": "Kleine, nützliche Tools verwandt zum Hauptprodukt bauen. Side-Projects ziehen Nutzer an und generieren Backlinks.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Tool-Idee validieren (z.B. DSGVO-Checker)", "MVP in 1-2 Wochen bauen", "Auf Product Hunt launchen"],
     "aidsec": "Kostenloser DSGVO-Website-Checker oder Cookie-Scanner als Lead-Magnet"},
    {"nr": 30, "name": "Engineering as Marketing", "cat": "Free Tools & Engineering",
     "desc": "Kostenlose Tools bauen, die echte Probleme der Zielgruppe lösen. Rechner, Analyser, Generatoren.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Pain-Point der Zielgruppe identifizieren", "Kostenloses Tool bauen", "E-Mail-Gate für detaillierte Ergebnisse"],
     "aidsec": "Security-Header-Checker ist bereits implementiert — Basis für weitere Tools"},
    {"nr": 31, "name": "Importers as Marketing", "cat": "Free Tools & Engineering",
     "desc": "Import-Tools für Konkurrenz-Daten bauen. 'Von [Konkurrent] importieren' reduziert Wechselfriction.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Gängige Konkurrenz-Formate analysieren", "1-Klick-Import-Tool bauen", "Migration-Guide erstellen"],
     "aidsec": "Import von Sucuri/Wordfence-Konfigurationen als Wechsel-Erleichterung"},
    {"nr": 92, "name": "Quiz Marketing", "cat": "Free Tools & Engineering",
     "desc": "Interaktive Quizzes für Engagement und Lead-Qualifizierung. Persönlichkeits-Tests, Assessments, Diagnose-Tools.",
     "budget": "low", "time": "quick", "stages": ["early", "growth"],
     "how": ["Quiz konzipieren ('Wie sicher ist Ihre Website?')", "E-Mail-Gate vor Ergebnissen", "Ergebnisse mit Produktempfehlung"],
     "aidsec": "'Website-Sicherheits-Check in 60 Sekunden' Quiz als Lead-Generator"},
    {"nr": 93, "name": "Calculator Marketing", "cat": "Free Tools & Engineering",
     "desc": "Rechner für echte Probleme bauen — ROI-Rechner, Preisschätzer, Einspar-Tools. Ziehen Links an und ranken gut.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Relevanten Rechner identifizieren", "Interaktives Tool erstellen", "Ergebnis-Seite mit CTA"],
     "aidsec": "'Datenverlust-Kostenrechner für Praxen' — zeigt Risiko-Kosten vs. AidSec-Preis"},
    {"nr": 94, "name": "Chrome Extensions", "cat": "Free Tools & Engineering",
     "desc": "Browser-Erweiterungen mit eigenständigem Nutzen erstellen. Chrome Web Store als Distributionskanal.",
     "budget": "medium", "time": "long", "stages": ["growth", "scale"],
     "how": ["Nützliche Extension konzipieren", "Entwickeln und im Chrome Store veröffentlichen", "In-Extension-Link zum Hauptprodukt"],
     "aidsec": "Chrome-Extension: 'Security Header Checker' — prüft jede besuchte Seite"},
    {"nr": 110, "name": "Microsites", "cat": "Free Tools & Engineering",
     "desc": "Fokussierte Microsites für spezifische Kampagnen, Produkte oder Zielgruppen. Eigene Domains ranken schneller.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Domain für spezifisches Thema registrieren", "Fokussierte Landing-Page erstellen", "SEO optimieren"],
     "aidsec": "Microsite: 'praxis-sicherheit.ch' oder 'kanzlei-schutz.ch' als Landing-Pages"},
    {"nr": 117, "name": "Scanners", "cat": "Free Tools & Engineering",
     "desc": "Kostenlose Scan-Tools, die etwas für den Nutzer auditieren oder analysieren. Website-Scanner, Security-Checker.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Scanner-Tool konzipieren", "Online-Version bauen", "Ergebnisse als Lead-Magnet nutzen"],
     "aidsec": "BEREITS IMPLEMENTIERT: Security-Ranking-Scanner im Dashboard — Basis vorhanden"},
    {"nr": 122, "name": "Public APIs", "cat": "Free Tools & Engineering",
     "desc": "Offene APIs ermöglichen Entwicklern, auf Ihrer Plattform aufzubauen. Ökosystem schaffen.",
     "budget": "medium", "time": "long", "stages": ["scale"],
     "how": ["API-Endpunkte definieren", "Dokumentation erstellen", "Developer-Portal aufbauen"],
     "aidsec": "Security-Check-API für Agenturen und IT-Dienstleister"},

    # ── Paid Advertising ───────────────────────────────────────────
    {"nr": 18, "name": "Podcast Advertising", "cat": "Paid Advertising",
     "desc": "Relevante Podcasts sponsern, um engagierte Zielgruppen zu erreichen. Host-gelesene Werbung funktioniert besonders gut.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Schweizer Business/Tech-Podcasts recherchieren", "Sponsoring-Pakete anfragen", "Tracking-URL erstellen"],
     "aidsec": "Schweizer KMU-Podcasts sponsern: 'Praxis digital', 'Legal Tech CH'"},
    {"nr": 48, "name": "Pre-targeting Ads", "cat": "Paid Advertising",
     "desc": "Awareness-Ads vor Direct-Response-Kampagnen schalten. Aufgewärmte Zielgruppen konvertieren besser.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Awareness-Kampagne mit Branding-Inhalten", "1-2 Wochen laufen lassen", "Dann Conversion-Kampagne starten"],
     "aidsec": "Erst Bewusstsein für Website-Sicherheitsrisiken schaffen, dann AidSec bewerben"},
    {"nr": 55, "name": "Facebook Ads", "cat": "Paid Advertising",
     "desc": "Metas detailliertes Targeting erreicht spezifische Zielgruppen. Creative-Varianten testen und Retargeting nutzen.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Zielgruppe definieren (Ärzte, Anwälte)", "Ad-Creatives erstellen", "A/B-Tests durchführen"],
     "aidsec": "Facebook/Instagram-Ads an Praxis-Inhaber und Kanzlei-Partner in der Schweiz"},
    {"nr": 57, "name": "Instagram Ads", "cat": "Paid Advertising",
     "desc": "Visuelle Werbung für Produkte mit starker Bildsprache. Stories und Reels Ads im nativen Format.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Visuell ansprechende Creatives erstellen", "Stories/Reels-Format nutzen", "Link zur Landing-Page"],
     "aidsec": "Vorher/Nachher Security-Grade (F→A) als visuelles Ad-Konzept"},
    {"nr": 60, "name": "Twitter Ads", "cat": "Paid Advertising",
     "desc": "Engagierte Fachleute erreichen, die über Branchenthemen diskutieren. Promoted Tweets und Follower-Kampagnen.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Keyword-Targeting auf Security-Begriffe", "Promoted Posts mit Mehrwert", "Engagement-Metriken tracken"],
     "aidsec": "X/Twitter-Ads an Schweizer IT-Entscheider und Praxis-Manager"},
    {"nr": 62, "name": "LinkedIn Ads", "cat": "Paid Advertising",
     "desc": "Nach Jobtitel, Unternehmensgrösse und Branche targeten. Premium-CPMs gerechtfertigt durch B2B-Kaufabsicht.",
     "budget": "high", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Zielgruppe nach Jobtitel filtern (Praxisinhaber, Partner)", "Sponsored Content erstellen", "Lead-Gen-Forms nutzen"],
     "aidsec": "TOP-KANAL: LinkedIn-Ads direkt an Praxisinhaber, Kanzlei-Partner, IT-Verantwortliche"},
    {"nr": 64, "name": "Reddit Ads", "cat": "Paid Advertising",
     "desc": "Leidenschaftliche Communities mit authentischer Botschaft erreichen. Reddit-Nutzer erkennen unechte Werbung sofort.",
     "budget": "low", "time": "quick", "stages": ["growth"],
     "how": ["Relevante Subreddits identifizieren", "Authentische Ad-Botschaft erstellen", "Transparenz betonen"],
     "aidsec": "r/cybersecurity, r/sysadmin, r/Switzerland mit Security-Tipps"},
    {"nr": 66, "name": "Quora Ads", "cat": "Paid Advertising",
     "desc": "Nutzer erreichen, die aktiv Fragen stellen, die das Produkt beantwortet. Intent-reiche Umgebung.",
     "budget": "low", "time": "quick", "stages": ["growth"],
     "how": ["Relevante Fragen identifizieren", "Gezielte Ads erstellen", "Landing-Page optimieren"],
     "aidsec": "Ads bei Fragen wie 'Wie schütze ich meine WordPress-Seite?'"},
    {"nr": 68, "name": "Google Ads", "cat": "Paid Advertising",
     "desc": "High-Intent-Suchanfragen abfangen. Marken-Begriffe schützen, Konkurrenz-Begriffe capturen, Kategorie-Begriffe erreichen.",
     "budget": "medium", "time": "quick", "stages": ["early", "growth", "scale"],
     "how": ["Keyword-Set zusammenstellen", "Anzeigen erstellen und Landing-Pages optimieren", "Conversion-Tracking einrichten"],
     "aidsec": "Google Ads: 'Website Sicherheit Praxis', 'WordPress Sicherheit Schweiz'"},
    {"nr": 70, "name": "YouTube Ads", "cat": "Paid Advertising",
     "desc": "Video-Ads mit detailliertem Targeting. Pre-Roll und Discovery Ads erreichen Nutzer bei verwandten Inhalten.",
     "budget": "medium", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Kurzes Erklär-Video produzieren", "YouTube-Targeting einrichten", "Retargeting-Pixel setzen"],
     "aidsec": "Pre-Roll vor Security-Videos: 'Ist Ihre Praxis-Website sicher?'"},
    {"nr": 72, "name": "Cross-Platform Retargeting", "cat": "Paid Advertising",
     "desc": "Nutzer plattformübergreifend mit konsistenter Botschaft verfolgen. Retargeting verwandelt Schaufenster-Shopper in Käufer.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Pixel auf allen Plattformen einrichten", "Retargeting-Audiences erstellen", "Sequenzielles Messaging aufbauen"],
     "aidsec": "Website-Besucher über Google, LinkedIn und Facebook erneut ansprechen"},
    {"nr": 129, "name": "Click-to-Messenger Ads", "cat": "Paid Advertising",
     "desc": "Ads, die direkte Gespräche statt Landing-Pages öffnen. Höheres Engagement durch sofortigen Dialog.",
     "budget": "medium", "time": "quick", "stages": ["growth"],
     "how": ["WhatsApp Business oder Messenger einrichten", "Click-to-Chat-Ad erstellen", "Schnelle Antwort-Templates vorbereiten"],
     "aidsec": "WhatsApp-Chat-Ad: 'Lassen Sie Ihre Praxis-Website kostenlos prüfen'"},

    # ── Social Media & Community ───────────────────────────────────
    {"nr": 42, "name": "Community Marketing", "cat": "Social Media & Community",
     "desc": "Communities aufbauen und pflegen. Slack-Gruppen, Discord-Server, Facebook-Gruppen oder Foren schaffen loyale Fürsprecher.",
     "budget": "free", "time": "long", "stages": ["early", "growth"],
     "how": ["Plattform wählen (LinkedIn-Gruppe, Slack)", "Wöchentliche Inhalte und Diskussionen", "Mitglieder als Botschafter gewinnen"],
     "aidsec": "LinkedIn-Gruppe: 'Cybersicherheit für Schweizer Praxen & Kanzleien'"},
    {"nr": 43, "name": "Quora Marketing", "cat": "Social Media & Community",
     "desc": "Relevante Fragen mit echtem Fachwissen beantworten. Produkterwähnungen wo natürlich passend.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Relevante Fragen zu Website-Sicherheit finden", "Ausführlich und kompetent antworten", "Dezent auf AidSec verweisen"],
     "aidsec": "Fragen zu WordPress-Sicherheit und Datenschutz beantworten"},
    {"nr": 76, "name": "Reddit Keyword Research", "cat": "Social Media & Community",
     "desc": "Reddit nach echten Formulierungen der Zielgruppe durchsuchen. Schmerzpunkte, Einwände und Wünsche entdecken.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Relevante Subreddits durchsuchen", "Häufige Beschwerden/Fragen notieren", "Formulierungen in Marketing übernehmen"],
     "aidsec": "Echte Sorgen von Ärzten/Anwälten zu IT-Sicherheit als Messaging nutzen"},
    {"nr": 82, "name": "Reddit Marketing", "cat": "Social Media & Community",
     "desc": "Authentisch in relevanten Subreddits teilnehmen. Zuerst Mehrwert bieten; Werbung scheitert ohne Glaubwürdigkeit.",
     "budget": "free", "time": "long", "stages": ["early", "growth"],
     "how": ["Account aufbauen und aktiv kommentieren", "Hilfreiche Security-Tipps teilen", "Nur bei passender Gelegenheit AidSec erwähnen"],
     "aidsec": "In r/Switzerland oder r/sysadmin als Security-Experte positionieren"},
    {"nr": 105, "name": "LinkedIn Audience", "cat": "Social Media & Community",
     "desc": "Personal Brands auf LinkedIn für B2B-Reichweite aufbauen. Thought-Leadership-Content baut Autorität auf.",
     "budget": "free", "time": "medium", "stages": ["early", "growth", "scale"],
     "how": ["Wöchentlich posten (Security-Insights, Tipps)", "Mit Zielgruppe interagieren", "Persönliche Stories mit Fachwissen verbinden"],
     "aidsec": "TOP-PRIORITÄT: Aid Destani als Cybersecurity-Experte auf LinkedIn positionieren"},
    {"nr": 106, "name": "Instagram Audience", "cat": "Social Media & Community",
     "desc": "Visuelles Storytelling für Produkte mit starker Ästhetik. Behind-the-Scenes, User-Stories, Produkt-Showcases.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Visuelles Branding definieren", "Regelmässig Security-Tipps als Grafiken posten", "Stories für Behind-the-Scenes"],
     "aidsec": "Security-Infografiken und Vorher/Nachher-Grades auf Instagram"},
    {"nr": 107, "name": "X Audience", "cat": "Social Media & Community",
     "desc": "Präsenz auf X/Twitter durch konsistenten Mehrwert aufbauen. Threads, Insights und Engagement bauen Followings auf.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Tägliche Security-Tipps/News teilen", "Threads zu Security-Themen schreiben", "Mit Branchenexperten interagieren"],
     "aidsec": "X-Threads: 'Die 7 Security Headers die jede Praxis-Website braucht'"},
    {"nr": 130, "name": "Short Form Video", "cat": "Social Media & Community",
     "desc": "TikTok, Reels und Shorts erreichen neue Zielgruppen mit Snackable Content. Lehrreiche Kurzvideos verbreiten sich organisch.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Kurze Security-Tipps als Reels produzieren", "Auf TikTok, Instagram, YouTube Shorts posten", "Trending Formate nutzen"],
     "aidsec": "'60-Sekunden Security-Check' oder 'Ist Ihre Website sicher?' als Kurzvideos"},
    {"nr": 138, "name": "Engagement Pods", "cat": "Social Media & Community",
     "desc": "Mit Peers koordinieren, um gegenseitig Content-Engagement zu boosten. Frühes Engagement hilft bei der Reichweite.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["5-10 ähnliche Unternehmer finden", "Gegenseitig Posts liken/kommentieren", "Konsistent durchführen"],
     "aidsec": "Mit anderen Schweizer IT-Dienstleistern Content-Engagement teilen"},
    {"nr": 139, "name": "Comment Marketing", "cat": "Social Media & Community",
     "desc": "Durchdachte Kommentare auf relevanten Inhalten bauen Sichtbarkeit auf. Mehrwert in Diskussionen der Zielgruppe.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Relevante LinkedIn/Twitter-Accounts folgen", "Mehrwert-Kommentare schreiben", "Konsequent beitragen"],
     "aidsec": "Auf LinkedIn-Posts von Ärzteverbänden und Anwaltsvereinigungen kommentieren"},

    # ── Email Marketing ────────────────────────────────────────────
    {"nr": 17, "name": "Mistake Email Marketing", "cat": "Email Marketing",
     "desc": "'Ups'-E-Mails bei echten Fehlern senden. Authentizität und Transparenz generieren oft höheres Engagement.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Bei Fehler sofort transparent kommunizieren", "Menschlichen Ton verwenden", "Lösung/Korrektur mitliefern"],
     "aidsec": "Authentische Fehler-Kommunikation stärkt Vertrauen bei Security-Kunden"},
    {"nr": 25, "name": "Reactivation Emails", "cat": "Email Marketing",
     "desc": "Churned oder inaktive Nutzer mit gezielten Kampagnen zurückgewinnen. An Nutzen erinnern, Neuigkeiten teilen.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Inaktive Leads identifizieren", "Personalisierte Reaktivierungs-Mail erstellen", "Neuen Nutzen/Feature hervorheben"],
     "aidsec": "BEREITS IMPLEMENTIERT: Outreach-System mit Nachfassen und intelligenter Personalisierung"},
    {"nr": 28, "name": "Founder Welcome Email", "cat": "Email Marketing",
     "desc": "Persönliche Willkommens-E-Mails vom Gründer schaffen Verbindung. Geschichte teilen, nach Zielen fragen.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Persönliche Willkommensmail von Aid schreiben", "Story und Mission teilen", "Frage stellen für Engagement"],
     "aidsec": "Aid Destani als persönlicher Sicherheitsberater — Welcome-Mail-Konzept vorhanden"},
    {"nr": 36, "name": "Dynamic Email Capture", "cat": "Email Marketing",
     "desc": "Intelligente E-Mail-Erfassung, die sich dem Nutzerverhalten anpasst. Exit-Intent, Scroll-Tiefe, Zeit auf Seite.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Exit-Intent-Popup auf Website einrichten", "Lead-Magnet anbieten (Security-Checkliste)", "A/B-Tests der Trigger"],
     "aidsec": "'Kostenlose Security-Checkliste für Ihre Praxis' als Exit-Intent-Popup"},
    {"nr": 79, "name": "Monthly Newsletters", "cat": "Email Marketing",
     "desc": "Konsistente Newsletter halten Ihre Marke präsent. Branchennews kuratieren, Insights teilen, Updates hervorheben.",
     "budget": "free", "time": "medium", "stages": ["early", "growth", "scale"],
     "how": ["Newsletter-Template erstellen", "Monatlich Security-News kuratieren", "Eigene Insights und Tipps einbauen"],
     "aidsec": "Monatlicher 'AidSec Security Brief' mit Bedrohungslage und Tipps"},
    {"nr": 80, "name": "Inbox Placement", "cat": "Email Marketing",
     "desc": "Technische E-Mail-Optimierung für Zustellbarkeit. Authentifizierung, Listenhygiene und Engagement-Signale.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["SPF, DKIM, DMARC prüfen und konfigurieren", "Inaktive Adressen entfernen", "Engagement-Rate verbessern"],
     "aidsec": "BEREITS KONFIGURIERT: Brevo SMTP mit SPF/DKIM/DMARC für aidsec.ch"},
    {"nr": 113, "name": "Onboarding Emails", "cat": "Email Marketing",
     "desc": "Neue Nutzer mit gezielten E-Mail-Sequenzen zur Aktivierung führen. Verhaltensgesteuert schlägt zeitbasiert.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Onboarding-Sequenz planen", "Trigger-basierte E-Mails einrichten", "Conversion-Punkte messen"],
     "aidsec": "Nach Security-Check: automatische Folge-Mails mit Handlungsempfehlungen"},
    {"nr": 115, "name": "Win-back Emails", "cat": "Email Marketing",
     "desc": "Verlorene Kunden mit Gründen zur Rückkehr re-engagieren. Neue Features, Verbesserungen oder Angebote.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Verlorene Leads identifizieren", "Neue Features/Verbesserungen hervorheben", "Spezielles Rückkehr-Angebot"],
     "aidsec": "Leads mit Status 'verloren' mit neuen Security-Bedrohungen reaktivieren"},
    {"nr": 116, "name": "Trial Reactivation", "cat": "Email Marketing",
     "desc": "Abgelaufene Testphasen sind keine verlorenen Fälle. Gezielte Kampagnen mit neuem Mehrwert können sie zurückholen.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Abgelaufene Trials identifizieren", "Personalisierte Reaktivierungs-Mail", "Zeitlimitiertes Angebot"],
     "aidsec": "Nach kostenlosem Security-Check: Erinnerung an kritische Ergebnisse senden"},

    # ── Partnerships & Programs ────────────────────────────────────
    {"nr": 9, "name": "Affiliate Discovery Through Backlinks", "cat": "Partnerships & Programs",
     "desc": "Potenzielle Affiliates durch Analyse von Konkurrenz-Backlinks finden. Wer verlinkt, bewirbt vielleicht auch.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Backlinks der Konkurrenz analysieren", "Blogs/Seiten identifizieren die verlinken", "Affiliate-Partnerschaft vorschlagen"],
     "aidsec": "IT-Blogs die auf Sucuri/Wordfence verlinken als potenzielle AidSec-Partner"},
    {"nr": 27, "name": "Influencer Whitelisting", "cat": "Partnerships & Programs",
     "desc": "Ads über Influencer-Accounts für authentische Reichweite schalten. Glaubwürdigkeit mit bezahltem Targeting kombinieren.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Relevante Influencer identifizieren", "Whitelisting-Vereinbarung treffen", "Ads über deren Account schalten"],
     "aidsec": "Schweizer IT-Influencer oder Ärzteverband-Botschafter für authentische Werbung"},
    {"nr": 33, "name": "Reseller Programs", "cat": "Partnerships & Programs",
     "desc": "Agenturen und Dienstleister Ihr Produkt weiterverkaufen lassen. White-Label schafft investierte Vertriebspartner.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Reseller-Programm konzipieren", "White-Label-Option definieren", "Erste Partner akquirieren"],
     "aidsec": "Webagenturen als Reseller: bieten AidSec-Schutz ihren Praxis/Kanzlei-Kunden an"},
    {"nr": 37, "name": "Expert Networks", "cat": "Partnerships & Programs",
     "desc": "Netzwerke zertifizierter Experten aufbauen, die Ihr Produkt implementieren.",
     "budget": "low", "time": "long", "stages": ["growth", "scale"],
     "how": ["Zertifizierungsprogramm erstellen", "Erste Experten onboarden", "Verzeichnis auf Website"],
     "aidsec": "IT-Dienstleister als 'AidSec Certified Partner' für lokale Implementierung"},
    {"nr": 50, "name": "Newsletter Swaps", "cat": "Partnerships & Programs",
     "desc": "Gegenseitige Erwähnungen mit komplementären Newslettern austauschen. Neue Zielgruppen ohne Werbekosten.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Komplementäre Newsletter identifizieren", "Swap-Vereinbarung treffen", "Gegenseitige Erwähnung planen"],
     "aidsec": "Newsletter-Swap mit IT-Recht-Newsletter oder Praxis-Management-Newsletter"},
    {"nr": 51, "name": "Article Quotes", "cat": "Partnerships & Programs",
     "desc": "Experten-Zitate zu Journalisten und Publikationen beitragen. HARO verbindet Experten mit Autoren.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["HARO/Qwoted registrieren", "Auf Security-relevante Anfragen antworten", "Expertise als Zitat anbieten"],
     "aidsec": "Als Schweizer Cybersecurity-Experte Zitate zu Datenschutz-Artikeln liefern"},
    {"nr": 77, "name": "Pixel Sharing", "cat": "Partnerships & Programs",
     "desc": "Mit komplementären Unternehmen Remarketing-Audiences teilen. Reichweite durch strategische Datenpartnerschaften.",
     "budget": "low", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Komplementäre Partner identifizieren", "Pixel-Sharing-Vereinbarung treffen", "Datenschutzkonform umsetzen"],
     "aidsec": "Pixel-Sharing mit Webdesign-Agenturen die Praxis-Websites erstellen"},
    {"nr": 78, "name": "Shared Slack Channels", "cat": "Partnerships & Programs",
     "desc": "Geteilte Channels mit Partnern und Kunden erstellen. Direkte Kommunikationswege stärken Beziehungen.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Slack/Teams-Channel einrichten", "Partner und Top-Kunden einladen", "Regelmässig Insights teilen"],
     "aidsec": "Slack-Channel mit IT-Partner-Agenturen für schnelle Security-Abstimmung"},
    {"nr": 97, "name": "Affiliate Program", "cat": "Partnerships & Programs",
     "desc": "Strukturierte Provisionsprogramme für Empfehler. Affiliates werden motivierte Verkäufer.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Provisionsstruktur definieren (z.B. 20%)", "Tracking-System einrichten", "Erste Affiliates rekrutieren"],
     "aidsec": "Webagenturen/IT-Berater erhalten Provision für AidSec-Empfehlungen"},
    {"nr": 98, "name": "Integration Marketing", "cat": "Partnerships & Programs",
     "desc": "Gemeinsames Marketing mit Integrationspartnern. Kombinierte Zielgruppen und geteilte Promotion.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Integrationspartner identifizieren", "Gemeinsames Webinar oder Content", "Cross-Promotion in Newslettern"],
     "aidsec": "Gemeinsame Kampagne mit WordPress-Hosting-Anbietern oder Praxis-Software"},
    {"nr": 99, "name": "Community Sponsorship", "cat": "Partnerships & Programs",
     "desc": "Relevante Communities, Newsletter oder Publikationen sponsern. Abgestimmte Sponsorings bauen Markenbekanntheit.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Relevante Communities identifizieren", "Sponsoring-Pakete anfragen", "Branding-Materialien erstellen"],
     "aidsec": "Ärzteverband-Newsletter oder Anwaltsverein-Events sponsern"},

    # ── Events & Speaking ──────────────────────────────────────────
    {"nr": 15, "name": "Live Webinars", "cat": "Events & Speaking",
     "desc": "Lehrreiche Webinare demonstrieren Expertise und generieren Leads. Interaktive Formate schaffen Engagement.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Thema wählen ('nDSG für Ihre Praxis-Website')", "Zoom/Teams-Webinar planen", "E-Mail-Einladung an Leads"],
     "aidsec": "Webinar: 'Website-Sicherheit für Arztpraxen — Was das nDSG von Ihnen verlangt'"},
    {"nr": 53, "name": "Virtual Summits", "cat": "Events & Speaking",
     "desc": "Multi-Speaker-Online-Events ziehen Publikum durch verschiedene Perspektiven an.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Thema und Speaker planen", "Registrierungs-Page erstellen", "Speaker bewerben Event bei ihrem Publikum"],
     "aidsec": "Online-Summit: 'Schweizer KMU Cybersecurity 2026' mit Gastexperten"},
    {"nr": 87, "name": "Roadshows", "cat": "Events & Speaking",
     "desc": "Produkt auf Tour bringen und Kunden direkt treffen. Regionale Events schaffen persönliche Verbindungen.",
     "budget": "medium", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Schweizer Städte-Tour planen", "Lokale Veranstaltungsorte buchen", "Einladungen an regionale Leads"],
     "aidsec": "AidSec Security Roadshow: Zürich, Bern, Basel, Luzern — Live-Demos"},
    {"nr": 90, "name": "Local Meetups", "cat": "Events & Speaking",
     "desc": "Lokale Meetups in Schlüsselmärkten hosten oder besuchen. Persönliche Kontakte stärken Beziehungen.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Meetup.com-Gruppe erstellen", "Monatliches Security-Treffen organisieren", "Räumlichkeiten und Verpflegung"],
     "aidsec": "'Cybersecurity für Schweizer KMU' Meetup-Reihe in Zürich"},
    {"nr": 91, "name": "Meetup Sponsorship", "cat": "Events & Speaking",
     "desc": "Relevante Meetups sponsern. Essen, Räume oder Swag-Sponsoring erzeugt Goodwill.",
     "budget": "low", "time": "quick", "stages": ["early", "growth"],
     "how": ["Relevante Tech/Business-Meetups identifizieren", "Sponsoring anbieten", "AidSec-Branding präsentieren"],
     "aidsec": "WordPress-Meetups oder Legal-Tech-Events in der Schweiz sponsern"},
    {"nr": 103, "name": "Conference Speaking", "cat": "Events & Speaking",
     "desc": "Auf Branchenkonferenzen sprechen. Präsentationen zeigen Expertise und generieren Leads.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["CFPs bei relevanten Konferenzen einreichen", "Spannenden Talk vorbereiten", "Kontakte nach dem Talk knüpfen"],
     "aidsec": "Vorträge auf Swiss Cyber Storm, IT-SA oder Ärztekongress-Sicherheitssession"},
    {"nr": 126, "name": "Conferences", "cat": "Events & Speaking",
     "desc": "Eigene Konferenz hosten und zum Zentrum der Branche werden. User-Konferenzen stärken Communities.",
     "budget": "high", "time": "long", "stages": ["scale"],
     "how": ["Event-Konzept und Budget planen", "Location und Datum festlegen", "Speaker einladen und bewerben"],
     "aidsec": "'AidSec Security Day' — jährliche Konferenz für Schweizer KMU-Sicherheit"},
    {"nr": 132, "name": "Conference Sponsorship", "cat": "Events & Speaking",
     "desc": "Relevante Konferenzen für Markensichtbarkeit sponsern. Stand, Speaking-Slots und Teilnehmerlisten.",
     "budget": "high", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Relevante Konferenzen identifizieren", "Sponsoring-Pakete anfragen", "Stand-Materialien erstellen"],
     "aidsec": "Swiss Cyber Storm oder Legal-Tech-Konferenzen sponsern"},

    # ── PR & Media ─────────────────────────────────────────────────
    {"nr": 8, "name": "Media Acquisitions as Marketing", "cat": "PR & Media",
     "desc": "Newsletter, Podcasts oder Publikationen in Ihrem Bereich akquirieren. Eigene Medien bieten direkten Zugang.",
     "budget": "high", "time": "long", "stages": ["scale"],
     "how": ["Relevante Medien identifizieren", "Akquisitions-Gespräche führen", "Integration planen"],
     "aidsec": "Schweizer IT-Security-Blog oder Newsletter akquirieren"},
    {"nr": 52, "name": "Press Coverage", "cat": "PR & Media",
     "desc": "Nachrichtenwürdige Stories bei relevanten Publikationen pitchen. Launches, Daten und Trends schaffen Presseoptionen.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Pressemitteilung vorbereiten", "Schweizer Tech-Journalisten kontaktieren", "Einzigartige Daten/Insights anbieten"],
     "aidsec": "Pressemitteilung: 'Sicherheitslage Schweizer Arztpraxis-Websites alarmierend'"},
    {"nr": 84, "name": "Fundraising PR", "cat": "PR & Media",
     "desc": "Finanzierungsankündigungen für Presse nutzen. Runden signalisieren Validierung und schaffen News-Hooks.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Bei Meilenstein Pressemitteilung erstellen", "Tech-Medien kontaktieren", "Story mit Wachstumszahlen untermauern"],
     "aidsec": "Bei Erreichen von 100 Kunden: Pressemitteilung als Erfolgsgeschichte"},
    {"nr": 118, "name": "Documentaries", "cat": "PR & Media",
     "desc": "Dokumentar-Content über Ihre Branche oder Kunden erstellen. Langform-Storytelling baut tiefe Verbindung auf.",
     "budget": "medium", "time": "long", "stages": ["growth", "scale"],
     "how": ["Dokumentar-Konzept entwickeln", "Kunden-Stories filmen", "Auf YouTube und Website veröffentlichen"],
     "aidsec": "Doku: 'Cyberangriff auf eine Schweizer Praxis — Was hätte AidSec verhindert?'"},

    # ── Launches & Promotions ──────────────────────────────────────
    {"nr": 21, "name": "Black Friday Promotions", "cat": "Launches & Promotions",
     "desc": "Jährliche Deals schaffen Dringlichkeit und Akquisitions-Spitzen. Deal-Sucher werden Langzeitkunden.",
     "budget": "low", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Rabatt-Aktion planen (z.B. 30% auf Rapid Fix)", "E-Mail-Kampagne vorbereiten", "Landing-Page erstellen"],
     "aidsec": "Black Friday: 'Rapid Header Fix für CHF 343 statt 490 — nur diese Woche'"},
    {"nr": 22, "name": "Product Hunt Launch", "cat": "Launches & Promotions",
     "desc": "Strukturierte Product-Hunt-Launches erreichen Early Adopters. Vorbereitung, Timing und Community-Engagement.",
     "budget": "free", "time": "quick", "stages": ["pre_launch", "early"],
     "how": ["PH-Profil vorbereiten", "Community vorab mobilisieren", "Am Launch-Tag aktiv auf Kommentare antworten"],
     "aidsec": "AidSec Security Scanner als kostenloses Tool auf Product Hunt launchen"},
    {"nr": 23, "name": "Early-Access Referrals", "cat": "Launches & Promotions",
     "desc": "Referrals mit früherem Zugang bei Launches belohnen. Waitlist-Referralprogramme schaffen virale Vorfreude.",
     "budget": "free", "time": "quick", "stages": ["pre_launch"],
     "how": ["Waitlist mit Referral-Mechanismus einrichten", "Belohnung für Top-Referrer definieren", "Viral-Loop optimieren"],
     "aidsec": "Waitlist für neues AidSec-Feature mit Priority-Access für Empfehlungen"},
    {"nr": 44, "name": "New Year Promotions", "cat": "Launches & Promotions",
     "desc": "Neujahr bringt frische Budgets und Zielsetzungs-Energie. Promotion-Timing an Erneuerungs-Mentalität anpassen.",
     "budget": "low", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Januar-Aktion planen", "Neue-Vorsätze-Messaging nutzen", "Angebot zeitlich begrenzen"],
     "aidsec": "'Neues Jahr, sichere Website — Starten Sie 2026 geschützt' Kampagne"},
    {"nr": 54, "name": "Early Access Pricing", "cat": "Launches & Promotions",
     "desc": "Mit reduziertem Preis für Early Access launchen. Frühe Unterstützer bekommen Deals, Sie Testimonials.",
     "budget": "free", "time": "quick", "stages": ["pre_launch", "early"],
     "how": ["Reduziertes Einführungs-Angebot definieren", "Limitierung kommunizieren", "Testimonials einsammeln"],
     "aidsec": "Cyber Mandat Einführungspreis: CHF 69/Mt. für erste 20 Kunden statt 89"},
    {"nr": 58, "name": "Product Hunt Alternatives", "cat": "Launches & Promotions",
     "desc": "Auf Alternativen zu Product Hunt launchen — BetaList, Launching Next, AlternativeTo.",
     "budget": "free", "time": "quick", "stages": ["pre_launch", "early"],
     "how": ["Alle Launch-Plattformen identifizieren", "Profile erstellen", "Sequenziell launchen"],
     "aidsec": "AidSec auf BetaList, AlternativeTo und SaaSHub listen"},
    {"nr": 59, "name": "Twitter Giveaways", "cat": "Launches & Promotions",
     "desc": "Engagement-steigernde Giveaways mit Follows, Retweets oder Tags. Vergrössern Following und erzeugen Buzz.",
     "budget": "low", "time": "quick", "stages": ["early", "growth"],
     "how": ["Attraktiven Preis definieren", "Teilnahmebedingungen festlegen", "Gewinner öffentlich bekanntgeben"],
     "aidsec": "'Gewinne einen kostenlosen Rapid Header Fix' — RT + Follow zum Teilnehmen"},
    {"nr": 109, "name": "Giveaways", "cat": "Launches & Promotions",
     "desc": "Strategische Giveaways ziehen Aufmerksamkeit an und erfassen Leads.",
     "budget": "low", "time": "quick", "stages": ["early", "growth"],
     "how": ["Relevanten Preis wählen", "Lead-Capture einrichten", "Über mehrere Kanäle bewerben"],
     "aidsec": "Gratis Kanzlei-Härtung im Wert von CHF 950 als Lead-Generator"},
    {"nr": 119, "name": "Vacation Giveaways", "cat": "Launches & Promotions",
     "desc": "Grosspreise generieren massives Engagement. Traumreisen motivieren zum Teilen und Mitmachen.",
     "budget": "high", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Attraktiven Hauptpreis definieren", "Virale Teilnahmemechanik", "Social-Media-Promotion"],
     "aidsec": "Eher für grössere Kampagnen — bei AidSec eher Cyber-Mandat-Jahresabo als Preis"},
    {"nr": 140, "name": "Lifetime Deals", "cat": "Launches & Promotions",
     "desc": "Einmalzahlungs-Deals generieren Cash und Nutzer. Lifetime-Deal-Plattformen erreichen Deal-Jäger.",
     "budget": "free", "time": "quick", "stages": ["early"],
     "how": ["Lifetime-Angebot definieren", "Auf AppSumo/Dealify listen", "Support-Kapazität planen"],
     "aidsec": "Lifetime Rapid Header Fix für CHF 990 — einmalig, für immer geschützt"},

    # ── Product-Led Growth ─────────────────────────────────────────
    {"nr": 16, "name": "Powered By Marketing", "cat": "Product-Led Growth",
     "desc": "'Powered by [Produkt]' Badges auf Kunden-Output schaffen kostenlose Impressionen. Jeder Kunde wird Marketingkanal.",
     "budget": "free", "time": "quick", "stages": ["early", "growth", "scale"],
     "how": ["Badge-Design erstellen", "In Security-Report einbauen", "Link zur AidSec-Website"],
     "aidsec": "'Gesichert durch AidSec' Badge auf geschützten Websites"},
    {"nr": 19, "name": "Free Migrations", "cat": "Product-Led Growth",
     "desc": "Kostenlose Migrationsservices von Konkurrenten anbieten. Wechselfriction reduzieren.",
     "budget": "low", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Migrations-Service definieren", "Landing-Page erstellen", "Gezielte Kampagne starten"],
     "aidsec": "'Wechsel von Sucuri/Wordfence — kostenlose Migration'"},
    {"nr": 20, "name": "Contract Buyouts", "cat": "Product-Led Growth",
     "desc": "Konkurrenz-Verträge aufkaufen. Dramatisches Commitment entfernt die letzte Barriere.",
     "budget": "high", "time": "quick", "stages": ["scale"],
     "how": ["Buyout-Bedingungen definieren", "Gezielte Kampagne an Konkurrenz-Kunden", "ROI berechnen"],
     "aidsec": "Bei Enterprise-Kunden: bestehende Security-Verträge übernehmen"},
    {"nr": 32, "name": "One-Click Registration", "cat": "Product-Led Growth",
     "desc": "Anmelde-Friction mit One-Click-OAuth minimieren. Vorausgefüllte Formulare und sofortiger Zugang.",
     "budget": "low", "time": "quick", "stages": ["early", "growth"],
     "how": ["Google/LinkedIn OAuth einrichten", "Registrierungsformular minimieren", "Onboarding optimieren"],
     "aidsec": "1-Klick-Anmeldung für kostenlosen Security-Check"},
    {"nr": 69, "name": "In-App Upsells", "cat": "Product-Led Growth",
     "desc": "Strategische Upgrade-Prompts innerhalb des Produkterlebnisses. Kontextuelle Upsells konvertieren am besten.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Upsell-Punkte identifizieren", "Kontextuelle Prompts einbauen", "Conversion messen"],
     "aidsec": "Nach Security-Check Grade F: 'Jetzt Rapid Header Fix für Note A in 24h'"},
    {"nr": 71, "name": "Newsletter Referrals", "cat": "Product-Led Growth",
     "desc": "Eingebaute Referralprogramme für Newsletter und Content. Einfache Sharing-Mechanismen machen Abonnenten zu Promotern.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Referral-Link in Newsletter einbauen", "Belohnungsstufen definieren", "Tracking einrichten"],
     "aidsec": "'Empfehlen Sie den AidSec Security Brief — 3 Empfehlungen = kostenloser Security-Check'"},
    {"nr": 75, "name": "Viral Loops", "cat": "Product-Led Growth",
     "desc": "Produktmechaniken, die natürlich zum Teilen ermutigen. Kollaborations-Features oder Referral-Anreize.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Sharing-Mechanismus in Produkt einbauen", "Anreiz für Weiterleitung definieren", "Viral-Koeffizient messen"],
     "aidsec": "Security-Report teilbar machen: 'Unser Arzt hat Note A — hat Ihrer auch?'"},
    {"nr": 114, "name": "Offboarding Flows", "cat": "Product-Led Growth",
     "desc": "Kündigungsflows optimieren um zu halten oder zu lernen. Exit-Surveys, Spar-Angebote, Pause-Optionen.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Kündigungs-Survey einrichten", "Pause-Option anbieten", "Spezielles Halte-Angebot"],
     "aidsec": "Beim Cyber-Mandat-Kündigung: 'Pause für 1 Monat statt Kündigung?'"},
    {"nr": 124, "name": "Concierge Setup", "cat": "Product-Led Growth",
     "desc": "White-Glove Onboarding für hochwertige Accounts. Persönliche Setup-Hilfe steigert Aktivierung.",
     "budget": "low", "time": "quick", "stages": ["growth", "scale"],
     "how": ["VIP-Onboarding für Premium-Kunden definieren", "Persönlichen Ansprechpartner zuweisen", "Setup-Call anbieten"],
     "aidsec": "BEREITS VORHANDEN: Persönlicher Service durch Aid Destani für Kanzlei-Härtung"},
    {"nr": 127, "name": "Onboarding Optimization", "cat": "Product-Led Growth",
     "desc": "Kontinuierliche Verbesserung der Neu-Nutzer-Erfahrung. Schnellere Time-to-Value steigert Conversion.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Onboarding-Schritte analysieren", "Drop-off-Punkte identifizieren", "Iterativ verbessern"],
     "aidsec": "Security-Check → Ergebnis → Angebot Fluss optimieren"},

    # ── Content Formats ────────────────────────────────────────────
    {"nr": 1, "name": "Playlists as Marketing", "cat": "Content Formats",
     "desc": "Spotify-Playlists für Ihre Zielgruppe erstellen — Produktivitätsmusik, Arbeitsmusik. Tägliche Touchpoints.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Playlist-Konzept definieren", "Auf Spotify erstellen", "In Marketing-Kanälen teilen"],
     "aidsec": "'Focus Music for IT Security Pros' Playlist — kreatives Branding"},
    {"nr": 46, "name": "Template Marketing", "cat": "Content Formats",
     "desc": "Kostenlose Templates anbieten, die sofort nutzbar sind. Templates schaffen Gewohnheit und Abhängigkeit.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Nützliche Templates erstellen", "Als Download anbieten", "E-Mail-Gate einrichten"],
     "aidsec": "Security-Checkliste, DSGVO-Template, Incident-Response-Plan als Downloads"},
    {"nr": 49, "name": "Graphic Novel Marketing", "cat": "Content Formats",
     "desc": "Komplexe Stories in visuelle Narrativen verwandeln. Graphic Novels stechen heraus und machen abstrakte Konzepte greifbar.",
     "budget": "medium", "time": "long", "stages": ["growth", "scale"],
     "how": ["Story-Konzept entwickeln", "Illustrator beauftragen", "Als Marketing-Asset verteilen"],
     "aidsec": "Comic: 'Dr. Müllers Praxis wurde gehackt — So hätte es verhindert werden können'"},
    {"nr": 65, "name": "Promo Videos", "cat": "Content Formats",
     "desc": "Hochwertige Promotion-Videos präsentieren Ihr Produkt professionell. Investition in Produktionswert lohnt sich.",
     "budget": "medium", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Video-Konzept und Storyboard", "Professionell produzieren", "Auf Website, YouTube, Social teilen"],
     "aidsec": "Erklär-Video: 'In 24 Stunden von Note F zu A — So funktioniert AidSec'"},
    {"nr": 81, "name": "Industry Interviews", "cat": "Content Formats",
     "desc": "Kunden, Experten und Thought-Leader interviewen. Interview-Content baut Beziehungen und wertvolle Assets.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Interview-Partner identifizieren", "Fragen vorbereiten", "Als Blog/Video veröffentlichen"],
     "aidsec": "Interviews mit Praxis-Inhabern über IT-Sicherheit und deren Erfahrungen"},
    {"nr": 89, "name": "Social Screenshots", "cat": "Content Formats",
     "desc": "Teilbare Screenshot-Templates für Social Proof. Einfach für Kunden, Erfolge und Testimonials zu teilen.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Templates für Security-Grades erstellen", "Kunden ermutigen zu teilen", "Hashtag definieren"],
     "aidsec": "Teilbare Grade-A-Zertifikats-Grafik: 'Wir sind AidSec-geschützt'"},
    {"nr": 101, "name": "Online Courses", "cat": "Content Formats",
     "desc": "Lehrreiche Kurse etablieren Autorität und generieren Leads. Kostenlose Kurse ziehen Lerner an.",
     "budget": "low", "time": "long", "stages": ["growth", "scale"],
     "how": ["Kurs-Thema definieren", "Module erstellen", "Auf eigener Plattform oder Udemy anbieten"],
     "aidsec": "Kurs: 'Website-Sicherheit für Nicht-Techniker — Was Praxis-Inhaber wissen müssen'"},
    {"nr": 102, "name": "Book Marketing", "cat": "Content Formats",
     "desc": "Buch schreiben, das Expertise in Ihrer Domain etabliert. Bücher schaffen Glaubwürdigkeit und Sprecheinladungen.",
     "budget": "low", "time": "long", "stages": ["growth", "scale"],
     "how": ["Buchkonzept und Gliederung", "Schreiben und veröffentlichen", "Als Marketing-Tool einsetzen"],
     "aidsec": "E-Book: 'Das kleine 1x1 der Website-Sicherheit für Schweizer KMU'"},
    {"nr": 111, "name": "Annual Reports", "cat": "Content Formats",
     "desc": "Jährliche Berichte mit Branchendaten und Trends veröffentlichen. Originale Forschung wird verlinkbare Referenz.",
     "budget": "low", "time": "long", "stages": ["growth", "scale"],
     "how": ["Daten sammeln und analysieren", "Report professionell gestalten", "PR-Kampagne zum Launch"],
     "aidsec": "'AidSec Schweizer Website-Sicherheitsbericht 2026' — jährliches Flaggschiff-Content"},
    {"nr": 120, "name": "End of Year Wraps", "cat": "Content Formats",
     "desc": "Personalisierte Jahresend-Zusammenfassungen, die Nutzer teilen wollen. 'Spotify Wrapped' für Ihre Daten.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Daten pro Kunde aggregieren", "Visuelle Zusammenfassung erstellen", "Sharing-Mechanismus einbauen"],
     "aidsec": "'Ihr AidSec Jahresrückblick: X Bedrohungen abgewehrt, Note A seit Y Monaten'"},
    {"nr": 121, "name": "Podcasts", "cat": "Content Formats",
     "desc": "Podcast starten. Regelmässiger Audio-Content baut intime Zuhörer-Beziehungen auf.",
     "budget": "low", "time": "long", "stages": ["early", "growth"],
     "how": ["Podcast-Konzept und Format definieren", "Erste Episoden aufnehmen", "Auf allen Plattformen veröffentlichen"],
     "aidsec": "Podcast: 'Security Brief' — wöchentliche Cyber-Tipps für Schweizer KMU"},
    {"nr": 63, "name": "Changelogs", "cat": "Content Formats",
     "desc": "Öffentliche Changelogs zeigen Produkt-Momentum. Regelmässige Updates demonstrieren aktive Entwicklung.",
     "budget": "free", "time": "quick", "stages": ["early", "growth", "scale"],
     "how": ["Changelog-Seite auf Website erstellen", "Bei jedem Update aktualisieren", "In Newsletter einbinden"],
     "aidsec": "Öffentliches Changelog für AidSec-Dashboard-Features und Security-Updates"},
    {"nr": 112, "name": "Public Demos", "cat": "Content Formats",
     "desc": "Live-Produktdemonstrationen zeigen echte Nutzung. Transparente Demos bauen Vertrauen auf.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Demo-Flow vorbereiten", "Live-Demo aufnehmen oder streamen", "Auf Website einbinden"],
     "aidsec": "Live-Demo: 'Sehen Sie wie wir Note F zu A in 20 Minuten ändern'"},

    # ── Unconventional & Creative ──────────────────────────────────
    {"nr": 6, "name": "Awards as Marketing", "cat": "Unconventional & Creative",
     "desc": "Branchen-Awards erstellen, die Ihre Marke als Geschmacksgeber positionieren. Award-Programme ziehen Bewerbungen an.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Award-Kategorien definieren", "Bewerbungs-Prozess einrichten", "Gewinner öffentlich ehren"],
     "aidsec": "'AidSec Sicherheits-Award' für die sicherste Praxis/Kanzlei-Website der Schweiz"},
    {"nr": 10, "name": "Challenges as Marketing", "cat": "Unconventional & Creative",
     "desc": "Virale Challenges launchen, die sich organisch verbreiten. Kreative Challenges generieren User-Content.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Challenge-Konzept erstellen", "Hashtag definieren", "Erste Teilnehmer mobilisieren"],
     "aidsec": "'#SecurityCheckChallenge — Prüfen Sie Ihre Note und teilen Sie sie!'"},
    {"nr": 11, "name": "Reality TV Marketing", "cat": "Unconventional & Creative",
     "desc": "Reality-Show-Style Content über echte Kunden erstellen. Dokumentar-Wettbewerbsformate schaffen fesselnde Narrative.",
     "budget": "medium", "time": "long", "stages": ["growth", "scale"],
     "how": ["Konzept entwickeln", "Teilnehmer finden", "Episoden produzieren"],
     "aidsec": "'Security Makeover' — AidSec besucht unsichere Praxis-Websites und transformiert sie"},
    {"nr": 12, "name": "Controversy as Marketing", "cat": "Unconventional & Creative",
     "desc": "Strategische Positionierung gegen Branchennormen. Konträre Meinungen erzeugen Aufmerksamkeit und Diskussion.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Konträre aber vertretbare Position formulieren", "Content dazu erstellen", "Diskussion moderieren"],
     "aidsec": "'Ihr Webentwickler hat KEINE Ahnung von Sicherheit — und das ist normal'"},
    {"nr": 13, "name": "Moneyball Marketing", "cat": "Unconventional & Creative",
     "desc": "Datengetriebenes Marketing findet unterbewertete Kanäle und Taktiken. Analytics identifizieren übersehene Chancen.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Alle Marketing-Kanäle analysieren", "Unterbewertete Kanäle identifizieren", "Budget umschichten"],
     "aidsec": "Dashboard-Daten nutzen um effektivste Outreach-Kanäle zu identifizieren"},
    {"nr": 14, "name": "Curation as Marketing", "cat": "Unconventional & Creative",
     "desc": "Wertvolle Ressourcen für Ihre Zielgruppe kuratieren. Verzeichnisse, Listen und Sammlungen bieten Mehrwert.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Thema für Kuratierung wählen", "Ressourcen sammeln und organisieren", "Regelmässig aktualisieren"],
     "aidsec": "'Schweizer Cybersecurity-Ressourcen für KMU' Verzeichnis als Lead-Magnet"},
    {"nr": 29, "name": "Grants as Marketing", "cat": "Unconventional & Creative",
     "desc": "Zuschüsse an Kunden oder Community anbieten. Grant-Programme generieren Bewerbungen, PR und Goodwill.",
     "budget": "medium", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Grant-Programm definieren", "Bewerbungsprozess erstellen", "Gewinner öffentlich bekanntgeben"],
     "aidsec": "'AidSec Sicherheits-Stipendium': 5 kostenlose Rapid Header Fixes pro Quartal für NGOs"},
    {"nr": 34, "name": "Product Competitions", "cat": "Unconventional & Creative",
     "desc": "Wettbewerbe mit Ihrem Produkt sponsern. Hackathons und Design-Contests zeigen Fähigkeiten.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Wettbewerbs-Format definieren", "Preise festlegen", "Community mobilisieren"],
     "aidsec": "'Security Header Hackathon' — bester Schutz für eine Test-Website gewinnt"},
    {"nr": 35, "name": "Cameo Marketing", "cat": "Unconventional & Creative",
     "desc": "Cameo-Prominente für personalisierte Marketing-Botschaften nutzen. Überraschende Celebrity-Endorsements erzeugen Buzz.",
     "budget": "medium", "time": "quick", "stages": ["growth"],
     "how": ["Relevanten Cameo-Promi finden", "Personalisierte Botschaft bestellen", "In Marketing einsetzen"],
     "aidsec": "Weniger relevant für B2B — aber humorvoller Security-Tipp von Promi möglich"},
    {"nr": 83, "name": "OOH Advertising", "cat": "Unconventional & Creative",
     "desc": "Out-of-Home-Werbung — Plakatwände, Transit-Ads. Physische Präsenz an Schlüsselstandorten.",
     "budget": "high", "time": "quick", "stages": ["scale"],
     "how": ["Standorte identifizieren (Spitäler, Gerichte)", "Design erstellen", "Kampagne buchen"],
     "aidsec": "Plakate bei Bezirksgerichten und Spitälern: 'Ist Ihre Website so sicher wie Ihre Praxis?'"},
    {"nr": 125, "name": "Marketing Stunts", "cat": "Unconventional & Creative",
     "desc": "Mutige, aufmerksamkeitserregende Marketing-Momente. Gut ausgeführte Stunts generieren Presse und Social Sharing.",
     "budget": "medium", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Stunt-Idee entwickeln", "Medien-Plan vorbereiten", "Dokumentation sicherstellen"],
     "aidsec": "Live Security-Audit einer bekannten Schweizer Website (mit Erlaubnis)"},
    {"nr": 128, "name": "Guerrilla Marketing", "cat": "Unconventional & Creative",
     "desc": "Unkonventionelles, kostengünstiges Marketing an unerwarteten Orten. Kreative Guerrilla-Taktiken stechen heraus.",
     "budget": "low", "time": "quick", "stages": ["early", "growth"],
     "how": ["Kreative Aktion planen", "An überraschendem Ort umsetzen", "Social-Media-Dokumentation"],
     "aidsec": "'Security-Sticker' in Arztpraxen und Kanzleien: 'Ist Ihre Website sicher? aidsec.ch'"},
    {"nr": 136, "name": "Humor Marketing", "cat": "Unconventional & Creative",
     "desc": "Humor einsetzen um aufzufallen und Erinnerbarkeit zu schaffen. Lustiger Content wird geteilt.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Humorvollen Content erstellen", "Auf Social Media posten", "Branding beibehalten"],
     "aidsec": "Security-Memes: 'Wenn dein Praxis-Website-Passwort noch 123456 ist...'"},

    # ── Platforms & Marketplaces ───────────────────────────────────
    {"nr": 24, "name": "Open Source as Marketing", "cat": "Platforms & Marketplaces",
     "desc": "Open-Source-Komponenten oder Tools bauen Developer-Goodwill auf. Open Source schafft Community.",
     "budget": "free", "time": "long", "stages": ["early", "growth"],
     "how": ["Nützliches Tool open-sourcen", "Auf GitHub veröffentlichen", "Community pflegen"],
     "aidsec": "Security-Header-Checker als Open-Source-Tool auf GitHub"},
    {"nr": 61, "name": "App Store Optimization", "cat": "Platforms & Marketplaces",
     "desc": "App-Store-Listings für Auffindbarkeit optimieren. Keywords, Screenshots und Bewertungen treiben Installs.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Keywords optimieren", "Screenshots und Beschreibung verbessern", "Bewertungen anfordern"],
     "aidsec": "Falls Mobile-App geplant: ASO für 'Website Sicherheit' Keywords"},
    {"nr": 86, "name": "App Marketplaces", "cat": "Platforms & Marketplaces",
     "desc": "In relevanten App-Marktplätzen und Verzeichnissen listen. Salesforce AppExchange, Shopify Store etc.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Relevante Marktplätze identifizieren", "Listings erstellen", "Bewertungen sammeln"],
     "aidsec": "WordPress Plugin Directory, Envato Market als Vertriebskanäle"},
    {"nr": 95, "name": "YouTube Reviews", "cat": "Platforms & Marketplaces",
     "desc": "YouTuber Ihr Produkt reviewen lassen. Authentische Reviews erreichen engagierte Zielgruppen.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Relevante YouTuber identifizieren", "Kostenlosen Zugang anbieten", "Review anfordern"],
     "aidsec": "WordPress-Security-YouTuber zum Review des AidSec-Security-Headers einladen"},
    {"nr": 96, "name": "YouTube Channel", "cat": "Platforms & Marketplaces",
     "desc": "YouTube-Präsenz mit Tutorials, Updates und Thought Leadership aufbauen. Video-Content gewinnt über Zeit.",
     "budget": "low", "time": "long", "stages": ["early", "growth"],
     "how": ["Kanal einrichten und branden", "Regelmässig Videos produzieren", "SEO für YouTube optimieren"],
     "aidsec": "AidSec YouTube: Security-Tutorials, Live-Demos, Kunden-Interviews"},
    {"nr": 108, "name": "Source Platforms", "cat": "Platforms & Marketplaces",
     "desc": "Auf Plattformen eintragen, die Tools und Produkte aggregieren. G2, Capterra, GetApp.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Auf G2, Capterra, GetApp registrieren", "Profil vollständig ausfüllen", "Bewertungen anfordern"],
     "aidsec": "WICHTIG: G2 und Capterra Listings für 'Website Security' Kategorie erstellen"},
    {"nr": 88, "name": "Review Sites", "cat": "Platforms & Marketplaces",
     "desc": "Präsenz auf Bewertungsplattformen aktiv managen. Bewertungen beeinflussen Kaufentscheidungen.",
     "budget": "free", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Alle Review-Plattformen identifizieren", "Aktiv Bewertungen anfordern", "Auf Feedback reagieren"],
     "aidsec": "Google Reviews, Trustpilot, G2 aktiv pflegen"},
    {"nr": 100, "name": "Live Audio", "cat": "Platforms & Marketplaces",
     "desc": "Live-Audio-Diskussionen auf Twitter Spaces, LinkedIn Audio. Echtzeit-Konversation schafft enges Engagement.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Regelmässigen Audio-Event planen", "Thema und Gäste definieren", "Auf Plattform hosten"],
     "aidsec": "LinkedIn Audio Event: 'Q&A — Website-Sicherheit für Schweizer Praxen'"},

    # ── International & Localization ───────────────────────────────
    {"nr": 133, "name": "International Expansion", "cat": "International & Localization",
     "desc": "In neue geografische Märkte expandieren. Lokalisierung, Partnerschaften und regionales Marketing.",
     "budget": "high", "time": "long", "stages": ["scale"],
     "how": ["Zielmarkt analysieren", "Lokalisierung durchführen", "Regionale Partner finden"],
     "aidsec": "Expansion nach Deutschland/Österreich — ähnliche Regulierung (DSGVO)"},
    {"nr": 134, "name": "Price Localization", "cat": "International & Localization",
     "desc": "Preise an lokale Kaufkraft anpassen. Lokalisierte Preise erhöhen Conversion in preissensiblen Märkten.",
     "budget": "free", "time": "quick", "stages": ["growth", "scale"],
     "how": ["Kaufkraft-Unterschiede analysieren", "Regionale Preise definieren", "Geo-Detection einrichten"],
     "aidsec": "EUR-Preise für DE/AT Markt neben CHF-Preisen anbieten"},

    # ── Developer & Technical ──────────────────────────────────────
    {"nr": 104, "name": "Investor Marketing", "cat": "Developer & Technical",
     "desc": "An Investoren vermarkten für Portfolio-Empfehlungen. Investoren empfehlen Tools an ihre Portfolio-Unternehmen.",
     "budget": "low", "time": "medium", "stages": ["early", "growth"],
     "how": ["Investor-Network-Events besuchen", "Pitch-Deck vorbereiten", "Follow-up pflegen"],
     "aidsec": "Schweizer VCs und Angels über AidSec informieren für Portfolio-Empfehlungen"},
    {"nr": 123, "name": "Certifications", "cat": "Developer & Technical",
     "desc": "Zertifizierungsprogramme schaffen, die Expertise validieren. Zertifizierte werden investierte Fürsprecher.",
     "budget": "low", "time": "long", "stages": ["growth", "scale"],
     "how": ["Zertifizierungs-Curriculum definieren", "Prüfung erstellen", "Zertifikat und Badge"],
     "aidsec": "'AidSec Certified Security Partner' für IT-Dienstleister"},
    {"nr": 131, "name": "Support as Marketing", "cat": "Developer & Technical",
     "desc": "Support-Interaktionen in Marketing-Möglichkeiten verwandeln. Aussergewöhnlicher Support wird zu Stories.",
     "budget": "free", "time": "quick", "stages": ["early", "growth", "scale"],
     "how": ["Support-Exzellenz als Priorität", "Positive Erfahrungen dokumentieren", "Als Testimonials nutzen"],
     "aidsec": "STÄRKE: Persönlicher Service durch Aid — Support-Stories als Marketing nutzen"},
    {"nr": 135, "name": "Developer Relations", "cat": "Developer & Technical",
     "desc": "Beziehungen zu Entwickler-Communities aufbauen. DevRel schafft Fürsprecher die Ihr Produkt empfehlen.",
     "budget": "low", "time": "long", "stages": ["growth", "scale"],
     "how": ["In Developer-Communities aktiv werden", "Technische Content erstellen", "Open-Source beitragen"],
     "aidsec": "WordPress-Developer-Community: Plugins, Tutorials, Stack Overflow Beiträge"},

    # ── Audience-Specific ──────────────────────────────────────────
    {"nr": 26, "name": "Two-Sided Referrals", "cat": "Audience-Specific",
     "desc": "Sowohl Empfehler als auch Empfohlenen belohnen. Doppelte Anreize motivieren zum Teilen.",
     "budget": "low", "time": "medium", "stages": ["growth", "scale"],
     "how": ["Belohnung für beide Seiten definieren", "Referral-System einrichten", "Tracking implementieren"],
     "aidsec": "Empfehler: CHF 50 Rabatt, Neukunde: 10% Rabatt auf Rapid Header Fix"},
    {"nr": 45, "name": "Podcast Tours", "cat": "Audience-Specific",
     "desc": "Als Gast auf mehreren Podcasts Ihre Zielgruppe erreichen. Podcast-Tours schaffen kumulierte Bekanntheit.",
     "budget": "free", "time": "medium", "stages": ["early", "growth"],
     "how": ["Relevante Podcasts recherchieren", "Pitch vorbereiten und anfragen", "Tour-Plan erstellen"],
     "aidsec": "Als Cybersecurity-Experte auf Schweizer Business/Health/Legal-Podcasts"},
    {"nr": 47, "name": "Customer Language", "cat": "Audience-Specific",
     "desc": "Die exakten Wörter Ihrer Kunden verwenden. Reviews, Support-Tickets und Interviews nach Sprache durchsuchen.",
     "budget": "free", "time": "quick", "stages": ["early", "growth", "scale"],
     "how": ["Kunden-Feedback sammeln", "Wiederkehrende Formulierungen identifizieren", "In Marketing-Copy übernehmen"],
     "aidsec": "Lead-Notizen und E-Mail-Antworten analysieren für authentisches Messaging"},
    {"nr": 85, "name": "Niche Directories", "cat": "Audience-Specific",
     "desc": "In branchenspezifischen Verzeichnissen listen. Nischen-Verzeichnisse erreichen hochqualifizierte Zielgruppen.",
     "budget": "free", "time": "quick", "stages": ["early", "growth"],
     "how": ["Relevante Branchenverzeichnisse finden", "Einträge erstellen", "Profile pflegen"],
     "aidsec": "Schweizer IT-Dienstleister-Verzeichnisse, Ärzteverband-Partner-Listen"},
]
# fmt: on


def get_ideas_by_category(category: str) -> List[Dict]:
    return [i for i in MARKETING_IDEAS if i["cat"] == category]


def filter_ideas(
    categories: Optional[List[str]] = None,
    budgets: Optional[List[str]] = None,
    timelines: Optional[List[str]] = None,
    stages: Optional[List[str]] = None,
    search: str = "",
) -> List[Dict]:
    results = MARKETING_IDEAS
    if categories:
        results = [i for i in results if i["cat"] in categories]
    if budgets:
        results = [i for i in results if i["budget"] in budgets]
    if timelines:
        results = [i for i in results if i["time"] in timelines]
    if stages:
        results = [i for i in results if any(s in i["stages"] for s in stages)]
    if search:
        q = search.lower()
        results = [
            i for i in results
            if q in i["name"].lower()
            or q in i["desc"].lower()
            or q in i.get("aidsec", "").lower()
        ]
    return results


def get_idea_by_nr(nr: int) -> Optional[Dict]:
    for i in MARKETING_IDEAS:
        if i["nr"] == nr:
            return i
    return None


def get_condensed_catalog() -> str:
    """Return a compact string of all ideas for LLM context."""
    lines = []
    for i in MARKETING_IDEAS:
        lines.append(f"#{i['nr']} {i['name']} [{i['cat']}] - {i['desc'][:80]}")
    return "\n".join(lines)
